kind: Deployment
apiVersion: apps/v1
metadata:
    name: nginx-deployment
    namespace: nginx-ns
    labels:
        app: nginx-pod
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx-pod
    template:
        metadata:
            name: nginx-dep-pod
            labels:
                app: nginx-pod
        spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: /var/www/html
                name: my-volume
            volumes:
              - name: my-volume
                persistentVolumeClaim:
                    claimName: local-pvc
