kind: PersistentVolume
apiVersion: v1
metadata:
    name: local-pv
    namespace: nginx-ns
    labels:
        app: local
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    PersistentVolumeReclaimPolicy: Retain
    stargeClassName: local-storage
    hostpath:
        path: /mnt/data