kind: DaemonSet
apiVersion: apps/v1
metadata:
    name: nginx-daemonsets
    namespace: nginx-ns
    labels:
        app: nginx-pod
spec:
    selector:
    matchLabels:
        app: nginx-pod

    template:
        metadata:
            name: nginx-dmn-pod
            labels:
                app: nginx-pod
        spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80