kind: DaemonSet
apiVersion: apps/v1
metadata:
    name: nginx-daemonsets
    namespace: nginx-ns
    labels:
        app: nginx-pod-dmn
spec:
    selector:
      matchLabels:
        app: nginx-pod-dmn

    template:
        metadata:
            name: nginx-dmn-pod
            labels:
                app: nginx-pod-dmn
        spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80
