kind: Job
apiVersion: batch/v1
metadata:
    name: demo-job
    namespace: nginx-ns
spec:
    completions: 1
    parallelism: 1

    template:
        metadata:
            name: demo-job-pod
            labels:
                app: batch-task
        spec:
            containers:
            - name: batch-container
              image: busybox:latest
              command: ["sh", "-c", "echo Hello everyone! && sleep 10"]
            restartPolicy: Never