kind: ReplicaSet
apiVersion: apps/v1
metadata:
    name: nginx-replicasets
    namespace: nginx-ns
    labels:
        app: nginx-pod-R
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx-pod-R
    
    template:
        metadata:
            name: nginx-rep-pod
            labels:
                app: nginx-pod-R
        spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
